### PR TITLE
Pyro revamp scripts

### PR DESCRIPTION
**Pull request by AfterShockFF**
Pyro loadout
* Raised starting rockets from 20 to 25
* Reduced napalm grenades from 2-4 to 1-2

Flamethrower
* Increased flamethrower base damage from 16 to 18
* Increased speed to deploy flamethrower from 0.5 to 0.2 seconds

Incendiary Cannon
* Increased IC refire rate to 0.6 seconds
* Increased speed to deploy IC from 0.5 to 0.2 seconds
* Increased base damage of IC from 55 to 65
* Reduced radius of IC blast from 125 to 110
* Reduced crosshair recoil of IC from 4 to 1
* Increased speed of IC reloading:
 * PreReloadTime from 0.4 to 0.1
 * Reload time from 1.2 to 0.65
 * Postreload time from 0.4 to 0.2
* Added clip to the IC, size 5

Misc
* Added jetpack sound

### CODE REVIEW

**Comment by squeek502** [comment]
@AfterShockFF make sure that this is up-to-date. Looks like some IC stuff (like increased clip size) has not been pushed yet.

Reminder to me/anyone else: The class description text/hints/etc will need to be updated.

**Comment by AfterShockFF** [comment]
good spot, done now

**Comment by MaxRideWizardLord** [comment]
So instead of improving his combat capabilities without making him rely on grenade much, you make it even more worthless?!

Don't care much about IC as it's damage is already so lame that pellet gun used as better damage source for mid\long range where IC serve as mere extra afterburn, but nerfing already weak flamethrower?

Flamethrower is his primary combat weapon, but it already have DPS very close of shotgun, while shotgun is mid range\secondary weapon and flamethrower is close range primary weapon. And of course, my idea to rework flamethrower for it to actually have ramp up damage for accurate aiming and get in melee range to deal with ambushed heavy classes was ignored... Not to mention flame particles are so bugged, that it can't damage anyone in corner, nor even hurt scout a little if he spam his nailgun in direction of flamethrower. Only because noob "le pr0" pickup scouts are too dumb and can't get a simple fact that you need to keep DISTANCE of pyro and not trying to overun him, neither tried to shot nailgun at him, doesn't excuse neither justifies such a retarded nerf, not to mention that a good soldier\medic already can take down good pyro, while hwguy and engineer are still hard counters.

Pyro didn't needed more mobility, he needed stopping power (more damage\dps) and that is something to not rely on combo nor grenades too much.

I guess people just can't accept that if a class is not as worthless as he was in TFC, people still will whine about "omg teh class is op, needs nerf asap!!111" and at best rework him in to FF scout, FF community never changes...

**Comment by squeek502** [comment]
These changes are part of a larger complete rework. See https://github.com/fortressforever/fortressforever/pull/270 for more info.

**Comment by MaxRideWizardLord** [comment]
> These changes are part of a complete rework of pyro. See fortressforever/fortressforever#270 for more info.

ugh, no shit? This is why my text adress to the whole pyro rework, I'm not really happy that instead of pyro we will have Scout №3. I think I'll just copy-paste the whole thing in the link you provided for that matter then.

**Pull request merged**
